2025/08/30 10:52:25: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       49768               1
=> RES: Exception on MESAPI CallAPI: Exception in MES1.MES_CORE :Cannot find table 0.
-------------------------------------
2025/08/30 10:52:25: MES1.EXCEPTION_SEND_MAIL
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       MES1.MES_CORE                                     http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Exception in MES1.MES_CORE :Cannot find table 0.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           {
  "IN_DB": "LGG",
  "IN_SP": "MES1.MES_CORE",
  "IN_EVENT": "LOGIN",
  "IN_DATA": "192.168.10.22       49768               1"
}
=> RES: MES1.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 10:53:02: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       49768               1
=> RES: Exception on MESAPI CallAPI: Exception in MES1.MES_CORE :Cannot find table 0.
-------------------------------------
2025/08/30 10:53:02: MES1.EXCEPTION_SEND_MAIL
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       MES1.MES_CORE                                     http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Exception in MES1.MES_CORE :Cannot find table 0.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           {
  "IN_DB": "LGG",
  "IN_SP": "MES1.MES_CORE",
  "IN_EVENT": "LOGIN",
  "IN_DATA": "192.168.10.22       49768               1"
}
=> RES: MES1.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 10:54:49: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       49768               1
=> RES: Exception on MESAPI CallAPI: Exception in MES1.MES_CORE :Cannot find table 0.
-------------------------------------
2025/08/30 10:54:49: MES1.EXCEPTION_SEND_MAIL
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       MES1.MES_CORE                                     http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Exception in MES1.MES_CORE :Cannot find table 0.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           {
  "IN_DB": "LGG",
  "IN_SP": "MES1.MES_CORE",
  "IN_EVENT": "LOGIN",
  "IN_DATA": "192.168.10.22       49768               1"
}
=> RES: MES1.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 10:55:51: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       49768               1
=> RES: Exception on MESAPI CallAPI: Exception in MES1.MES_CORE :Cannot find table 0.
-------------------------------------
2025/08/30 10:55:51: MES1.EXCEPTION_SEND_MAIL
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       MES1.MES_CORE                                     http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Exception in MES1.MES_CORE :Cannot find table 0.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           {
  "IN_DB": "LGG",
  "IN_SP": "MES1.MES_CORE",
  "IN_EVENT": "LOGIN",
  "IN_DATA": "192.168.10.22       49768               1"
}
=> RES: MES1.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 10:55:59: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       49768               1
=> RES: Exception on MESAPI CallAPI: Exception in MES1.MES_CORE :Cannot find table 0.
-------------------------------------
2025/08/30 10:55:59: MES1.EXCEPTION_SEND_MAIL
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       MES1.MES_CORE                                     http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Exception in MES1.MES_CORE :Cannot find table 0.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           {
  "IN_DB": "LGG",
  "IN_SP": "MES1.MES_CORE",
  "IN_EVENT": "LOGIN",
  "IN_DATA": "192.168.10.22       49768               1"
}
=> RES: MES1.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 11:05:01: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       49768               1
=> RES: Exception on MESAPI CallAPI: Object reference not set to an instance of an object.
-------------------------------------
2025/08/30 11:05:01: MES1.EXCEPTION_SEND_MAIL
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       MES1.MES_CORE                                     http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Object reference not set to an instance of an object.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
  "IN_DB": "LGG",
  "IN_SP": "MES1.MES_CORE",
  "IN_EVENT": "LOGIN",
  "IN_DATA": "192.168.10.22       49768               1"
}
=> RES: MES1.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 11:05:37: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       49768               1
=> RES: Exception on MESAPI CallAPI: Object reference not set to an instance of an object.
-------------------------------------
2025/08/30 11:05:37: MES1.EXCEPTION_SEND_MAIL
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       MES1.MES_CORE                                     http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Object reference not set to an instance of an object.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
  "IN_DB": "LGG",
  "IN_SP": "MES1.MES_CORE",
  "IN_EVENT": "LOGIN",
  "IN_DATA": "192.168.10.22       49768               1"
}
=> RES: MES1.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 11:07:32: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               1
=> RES: Exception on MESAPI CallAPI: Object reference not set to an instance of an object.
-------------------------------------
2025/08/30 11:07:32: MES1.EXCEPTION_SEND_MAIL
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       MES1.MES_CORE                                     http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Object reference not set to an instance of an object.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
  "IN_DB": "LGG",
  "IN_SP": "MES1.MES_CORE",
  "IN_EVENT": "LOGIN",
  "IN_DATA": "49768               1"
}
=> RES: MES1.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 11:07:36: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               1
=> RES: Exception on MESAPI CallAPI: Object reference not set to an instance of an object.
-------------------------------------
2025/08/30 11:07:36: MES1.EXCEPTION_SEND_MAIL
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       MES1.MES_CORE                                     http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Object reference not set to an instance of an object.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
  "IN_DB": "LGG",
  "IN_SP": "MES1.MES_CORE",
  "IN_EVENT": "LOGIN",
  "IN_DATA": "49768               1"
}
=> RES: MES1.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 11:08:01: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               1
=> RES: Exception on MESAPI CallAPI: Object reference not set to an instance of an object.
-------------------------------------
2025/08/30 11:08:01: MES1.EXCEPTION_SEND_MAIL
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       MES1.MES_CORE                                     http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Object reference not set to an instance of an object.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
  "IN_DB": "LGG",
  "IN_SP": "MES1.MES_CORE",
  "IN_EVENT": "LOGIN",
  "IN_DATA": "49768               1"
}
=> RES: MES1.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 11:08:20: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               1
=> RES: Exception on MESAPI CallAPI: Object reference not set to an instance of an object.
-------------------------------------
2025/08/30 11:08:20: MES1.EXCEPTION_SEND_MAIL
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       MES1.MES_CORE                                     http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Object reference not set to an instance of an object.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
  "IN_DB": "LGG",
  "IN_SP": "MES1.MES_CORE",
  "IN_EVENT": "LOGIN",
  "IN_DATA": "49768               1"
}
=> RES: MES1.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 11:11:21: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               ư
=> RES: Exception on MESAPI CallAPI: Object reference not set to an instance of an object.
-------------------------------------
2025/08/30 11:11:21: MES1.EXCEPTION_SEND_MAIL
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       MES1.MES_CORE                                     http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Object reference not set to an instance of an object.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
  "IN_DB": "LGG",
  "IN_SP": "MES1.MES_CORE",
  "IN_EVENT": "LOGIN",
  "IN_DATA": "49768               ư"
}
=> RES: MES1.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 11:11:49: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               q2
=> RES: Exception on MESAPI CallAPI: Object reference not set to an instance of an object.
-------------------------------------
2025/08/30 11:11:49: MES1.EXCEPTION_SEND_MAIL
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       MES1.MES_CORE                                     http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Object reference not set to an instance of an object.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
  "IN_DB": "LGG",
  "IN_SP": "MES1.MES_CORE",
  "IN_EVENT": "LOGIN",
  "IN_DATA": "49768               q2"
}
=> RES: MES1.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 11:15:15: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               1 
=> RES: Exception on MESAPI CallAPI: Object reference not set to an instance of an object.
-------------------------------------
2025/08/30 11:15:15: MES1.EXCEPTION_SEND_MAIL
- IN_EVENT: LOGIN
- IN_DATA: 192.168.10.22       MES1.MES_CORE                                     http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Object reference not set to an instance of an object.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {
  "IN_EVENT": "LOGIN",
  "IN_DATA": "49768               1 ",
  "IN_DB": "LGG",
  "IN_SP": "MES1.MES_CORE"
}
=> RES: MES1.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 11:16:32: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               1 
=> RES: OK ĐĂNG NHẬP THÀNH CÔNG 
-------------------------------------
2025/08/30 11:16:45: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               q2
=> RES: MẬT KHẨU HOẶC TÀI KHOẢN SAI
-------------------------------------
2025/08/30 11:16:49: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               1
=> RES: OK ĐĂNG NHẬP THÀNH CÔNG 
-------------------------------------
2025/08/30 11:16:49: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NG
-------------------------------------
2025/08/30 11:16:52: AP.MES_AMS
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: Exception on MESAPI CallAPI: Keyword not supported: 'unicode'.
-------------------------------------
2025/08/30 11:16:52: AP.EXCEPTION_SEND_MAIL
- IN_EVENT: ALL_PROJECT
- IN_DATA: 192.168.10.22       AP.MES_AMS                                        http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        10.220.117.33:1521/BTSSFC                                                                                                                                                                               Exception on MESAPI CallAPI: Keyword not supported: 'unicode'.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
  "IN_DB": "SFCTEST",
  "IN_SP": "AP.MES_AMS",
  "IN_EVENT": "ALL_PROJECT",
  "IN_DATA": "ALL_PROJECT"
}
=> RES: AP.EXCEPTION_SEND_MAIL Exception: Keyword not supported: 'unicode'.
-------------------------------------
2025/08/30 11:16:55: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NG
-------------------------------------
2025/08/30 11:17:43: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NG
-------------------------------------
2025/08/30 11:19:18: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NG
-------------------------------------
2025/08/30 11:19:19: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NG
-------------------------------------
2025/08/30 11:20:04: 
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 
=> RES: IN_DB is null
-------------------------------------
2025/08/30 11:20:12: 
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 
=> RES: IN_DB is null
-------------------------------------
2025/08/30 11:20:23: 
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 null
=> RES: IN_DB not exist in JSON input
-------------------------------------
2025/08/30 11:20:32: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               2
=> RES: MẬT KHẨU HOẶC TÀI KHOẢN SAI
-------------------------------------
2025/08/30 11:20:36: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               1
=> RES: OK ĐĂNG NHẬP THÀNH CÔNG 
-------------------------------------
2025/08/30 11:20:36: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NG
-------------------------------------
2025/08/30 11:20:36: MES1.MES_CORE
- IN_EVENT: GET_MENU
- IN_DATA: 49768               WEB
=> RES: NG
-------------------------------------
2025/08/30 11:20:43: AP.MES_AMS
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: Exception on MESAPI CallAPI: Keyword not supported: 'unicode'.
-------------------------------------
2025/08/30 11:20:43: AP.EXCEPTION_SEND_MAIL
- IN_EVENT: GET_INFOR_USER
- IN_DATA: 192.168.10.22       AP.MES_AMS                                        http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        10.220.117.33:1521/BTSSFC                                                                                                                                                                               Exception on MESAPI CallAPI: Keyword not supported: 'unicode'.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
  "IN_DB": "SFCTEST",
  "IN_SP": "AP.MES_AMS",
  "IN_EVENT": "GET_INFOR_USER",
  "IN_DATA": "undefined                                         "
}
=> RES: AP.EXCEPTION_SEND_MAIL Exception: Keyword not supported: 'unicode'.
-------------------------------------
2025/08/30 11:20:51: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NG
-------------------------------------
2025/08/30 11:25:07: 
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 null
=> RES: IN_DB not exist in JSON input
-------------------------------------
2025/08/30 11:26:58: AP.MES_AMS
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: Exception on MESAPI CallAPI: Keyword not supported: 'unicode'.
-------------------------------------
2025/08/30 11:26:58: AP.EXCEPTION_SEND_MAIL
- IN_EVENT: ALL_PROJECT
- IN_DATA: 192.168.10.22       AP.MES_AMS                                        http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        10.220.117.33:1521/BTSSFC                                                                                                                                                                               Exception on MESAPI CallAPI: Keyword not supported: 'unicode'.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
  "IN_DB": "SFCTEST",
  "IN_SP": "AP.MES_AMS",
  "IN_EVENT": "ALL_PROJECT",
  "IN_DATA": "ALL_PROJECT"
}
=> RES: AP.EXCEPTION_SEND_MAIL Exception: Keyword not supported: 'unicode'.
-------------------------------------
2025/08/30 11:27:05: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               1
=> RES: OK ĐĂNG NHẬP THÀNH CÔNG 
-------------------------------------
2025/08/30 11:27:05: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NG
-------------------------------------
2025/08/30 11:27:05: AP.MES_AMS
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: Exception on MESAPI CallAPI: Keyword not supported: 'unicode'.
-------------------------------------
2025/08/30 11:27:05: AP.MES_AMS
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: Exception on MESAPI CallAPI: Keyword not supported: 'unicode'.
-------------------------------------
2025/08/30 11:27:05: AP.EXCEPTION_SEND_MAIL
- IN_EVENT: ALL_PROJECT
- IN_DATA: 192.168.10.22       AP.MES_AMS                                        http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        10.220.117.33:1521/BTSSFC                                                                                                                                                                               Exception on MESAPI CallAPI: Keyword not supported: 'unicode'.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
  "IN_DB": "SFCTEST",
  "IN_SP": "AP.MES_AMS",
  "IN_EVENT": "ALL_PROJECT",
  "IN_DATA": "ALL_PROJECT"
}
=> RES: AP.EXCEPTION_SEND_MAIL Exception: Keyword not supported: 'unicode'.
-------------------------------------
2025/08/30 11:27:14: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NG
-------------------------------------
2025/08/30 11:27:20: AP.MES_AMS
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: Exception on MESAPI CallAPI: Keyword not supported: 'unicode'.
-------------------------------------
2025/08/30 11:27:20: AP.EXCEPTION_SEND_MAIL
- IN_EVENT: GET_INFOR_USER
- IN_DATA: 192.168.10.22       AP.MES_AMS                                        http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        10.220.117.33:1521/BTSSFC                                                                                                                                                                               Exception on MESAPI CallAPI: Keyword not supported: 'unicode'.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
  "IN_DB": "SFCTEST",
  "IN_SP": "AP.MES_AMS",
  "IN_EVENT": "GET_INFOR_USER",
  "IN_DATA": "undefined                                         "
}
=> RES: AP.EXCEPTION_SEND_MAIL Exception: Keyword not supported: 'unicode'.
-------------------------------------
2025/08/30 13:21:07: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               `
=> RES: MẬT KHẨU HOẶC TÀI KHOẢN SAI
-------------------------------------
2025/08/30 13:21:13: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               1
=> RES: OK ĐĂNG NHẬP THÀNH CÔNG 
-------------------------------------
2025/08/30 13:21:13: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 13:21:17: MES.IT_HELP_DESK
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: Exception on MESAPI CallAPI: Exception in MES.IT_HELP_DESK :Invalid SP Name, Please check SP: MES.IT_HELP_DESK
-------------------------------------
2025/08/30 13:21:17: MES.IT_HELP_DESK
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: Exception on MESAPI CallAPI: Exception in MES.IT_HELP_DESK :Invalid SP Name, Please check SP: MES.IT_HELP_DESK
-------------------------------------
2025/08/30 13:21:17: MES.EXCEPTION_SEND_MAIL
- IN_EVENT: GET_INFOR_USER
- IN_DATA: 192.168.10.22       MES.IT_HELP_DESK                                  http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Exception in MES.IT_HELP_DESK :Invalid SP Name, Please check SP: MES.IT_HELP_DESK                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
  "IN_DB": "LGG",
  "IN_SP": "MES.IT_HELP_DESK",
  "IN_EVENT": "GET_INFOR_USER",
  "IN_DATA": "undefined                                         "
}
=> RES: MES.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 13:21:17: MES.EXCEPTION_SEND_MAIL
- IN_EVENT: ALL_PROJECT
- IN_DATA: 192.168.10.22       MES.IT_HELP_DESK                                  http://192.168.10.22:8080/MESAPI/api/MES/CallAPI                                                                                                                                                        192.168.1.3                                                                                                                                                                                             Exception on MESAPI CallAPI: Exception in MES.IT_HELP_DESK :Invalid SP Name, Please check SP: MES.IT_HELP_DESK                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
  "IN_DB": "LGG",
  "IN_SP": "MES.IT_HELP_DESK",
  "IN_EVENT": "ALL_PROJECT",
  "IN_DATA": "ALL_PROJECT"
}
=> RES: MES.EXCEPTION_SEND_MAIL Exception: Invalid object name 'ALL_OBJECTS'.
-------------------------------------
2025/08/30 13:21:44: MES1.IT_HELP_DESK
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: NO EVENT!
-------------------------------------
2025/08/30 13:21:45: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 13:21:54: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 13:22:02: MES1.MES_AMS
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: IN_SP error: The SP: (MES1.MES_AMS) not exist on DB. Please call IT check!
-------------------------------------
2025/08/30 13:24:39: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 13:32:45: 
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 null
=> RES: IN_DB not exist in JSON input
-------------------------------------
2025/08/30 13:33:02: MES1.IT_HELP_DESK
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: NO EVENT!
-------------------------------------
2025/08/30 13:33:14: MES1.MES_CORE
- IN_EVENT: LOGIN
- IN_DATA: 49768               1
=> RES: OK ĐĂNG NHẬP THÀNH CÔNG 
-------------------------------------
2025/08/30 13:33:14: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 13:33:15: MES1.IT_HELP_DESK
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: NO EVENT!
-------------------------------------
2025/08/30 13:33:15: MES1.IT_HELP_DESK
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: NO EVENT!
-------------------------------------
2025/08/30 13:33:16: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 13:33:40: MES1.IT_HELP_DESK
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:45:43: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:45:49: MES1.MES_AMS
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: IN_SP error: The SP: (MES1.MES_AMS) not exist on DB. Please call IT check!
-------------------------------------
2025/08/30 14:45:49: MES1.MES_AMS
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: IN_SP error: The SP: (MES1.MES_AMS) not exist on DB. Please call IT check!
-------------------------------------
2025/08/30 14:45:51: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:45:56: MES1.IT_HELP_DESK
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:46:12: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:49:20: MES1.IT_HELP_DESK
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:49:23: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:49:28: MES1.IT_HELP_DESK
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:49:31: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:49:37: MES1.IT_HELP_DESK
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:49:45: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:49:53: MES1.IT_HELP_DESK
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:49:53: MES1.IT_HELP_DESK
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:50:44: MES1.IT_HELP_DESK
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:50:44: MES1.IT_HELP_DESK
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:50:45: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:50:51: MES1.IT_HELP_DESK
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:51:01: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:51:28: MES1.IT_HELP_DESK
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:51:37: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:52:33: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:52:54: MES1.IT_HELP_DESK
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:52:57: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:53:14: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:53:54: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:54:02: MES1.IT_HELP_DESK
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:54:02: MES1.IT_HELP_DESK
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:54:04: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:55:04: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:55:06: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:55:12: MES1.IT_HELP_DESK
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:55:14: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:55:24: MES1.IT_HELP_DESK
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:55:24: MES1.IT_HELP_DESK
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:55:32: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:56:11: MES1.IT_HELP_DESK
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:56:11: MES1.IT_HELP_DESK
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:56:13: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:58:18: MES1.MES_CORE
- IN_EVENT: CHECK_SECURITY
- IN_DATA: WEB                 192.168.10.22
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:58:24: MES1.IT_HELP_DESK
- IN_EVENT: GET_INFOR_USER
- IN_DATA: undefined                                         
=> RES: NO EVENT!
-------------------------------------
2025/08/30 14:58:24: MES1.IT_HELP_DESK
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: NO EVENT!
-------------------------------------
2025/08/30 15:10:12: MES1.IT_HELP_DESK
- IN_EVENT: MY_PROJECT
- IN_DATA: undefined                                         
=> RES: NO EVENT!
-------------------------------------
2025/08/30 15:10:15: MES1.IT_HELP_DESK
- IN_EVENT: SIGNED_PROJECT
- IN_DATA: undefined                                         
=> RES: NO EVENT!
-------------------------------------
2025/08/30 16:39:20: MES1.IT_HELP_DESK
- IN_EVENT: ALL_PROJECT
- IN_DATA: ALL_PROJECT
=> RES: NG
-------------------------------------
